### ISSUE TITLE
Support the rust-version field in a Cargo.toml. 

### ISSUE THREAD

**Issue by foresterre** [foresterre/cargo-msrv#136]
https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html

- [ ] Setting it when the msrv is found, and a flag is given (#328)
- [x] #141
- [ ] Resolving from package set (new find msrv method)
- [x] with above, limit search space

From 1.56.0
