### ISSUE TITLE
Tracking issue for v0.16

### ISSUE THREAD

**Issue by foresterre** [foresterre/cargo-msrv#409]
## Plan

**Docs**
- [ ] Update readme
- [ ] Update book
  - [x] Intro pages [#427]
  - [ ] Commands pages
  - [ ] Document output formats, [#386]
    - [ ] #527
    - [x] [#444]
    - [x] minimal
    - [x] discard 
  - [x] Add migration guide (esp. for JSON output)
  - [ ] Document exit code 
- [ ] Update changelog

**User output**
- [x] Consider last changes in user output formatting
  - [x] events
    - Also impacts json output since we use serde derive on the events
    - [x] Add `Event::SubcommandResult(SubcommandType)` to have a consistent output event for produced subcommand results; use serde tags [#437] 
  - [x] `human`
  - [x] `json`
- [x] Add `minimal` output option 
  - [#370]
  - [#436]
  - This should now be a breeze after #379 is merged 

**Features & fixes**
- [x] [#412]
- [x] revisit `TerminateWithFailure::is_error`
  - Clarify definition
  - Check which `Err` are unexpected, and which are event flow based
- [x] #486
- [x] #488

**Deps**
- [x] #491
- [x] #496 
- [x] Update `rust-releases` & update aws dependencies

**Misc**
- [ ] re-consider issues tracked in https://github.com/foresterre/cargo-msrv/milestone/3

**Blog**
- [ ] #574

## Moved to next release

**Features & fixes**
- [ ] [#408]
  - [ ] Replace [BareVersion](https://github.com/foresterre/cargo-msrv/blob/main/src/manifest/bare_version.rs) with https://github.com/foresterre/version-number
  - [ ] https://github.com/foresterre/version-number/issues/10 https://github.com/foresterre/version-number/pull/11
